name: Building docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Test
      runs:
        using: 'docker'
        image: 'Dockerfile'
