name: Building docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action step
            uses: ./ # Uses an action in the root directory
            id: hello